version: 2
updates:
  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: monthly
    groups:
      client-deps:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: "/server"
    schedule:
      interval: monthly
    groups:
      server-deps:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
